[package]
name = "hello-world"
version = "0.1.0"
description = "Neon Hello World"
authors = ["K.J. Valencik"]
license = "MIT"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]
